version: "3.6"
services:


  postgres:
    container_name: postgres
    build:
      context: ./postgres/
      dockerfile: Dockerfile
    ports:
      - "5432:5432"
#    restart: always
    networks:
      - msa-network


  discovery-service:
    container_name: discovery-service
    build:
      context: ./discovery-service/
      dockerfile: Dockerfile
    ports:
      - "8761:8761"
#    restart: always
    networks:
      - msa-network

  gateway-service:
    container_name: gateway-service
    build:
      context: ./gateway-servicee/
      dockerfile: Dockerfile
    environment:
      spring.profiles.active: prod
    ports:
      - "9000:9000"
    depends_on:
      - discovery-service
#    restart: always
    networks:
      - msa-network

  user-service:
    container_name: user-service
    build:
      context: ./user-service/
      dockerfile: Dockerfile
    environment:
      spring.profiles.active: prod
    ports:
      - "8010:8010"
    depends_on:
      - gateway-service
      - discovery-service
#    restart: always
    networks:
      - msa-network

  batch-service:
    container_name: batch-service
    build:
      context: ./batch-service/
      dockerfile: Dockerfile
    environment:
      spring.profiles.active: prod
    ports:
      - "8020:8020"
    depends_on:
      - gateway-service
      - discovery-service
#    restart: always
    networks:
      - msa-network

  business-service:
    container_name: business-service
    build:
      context: ./business-service/
      dockerfile: Dockerfile
    environment:
      spring.profiles.active: prod
    ports:
      - "8030:8030"
    depends_on:
      - gateway-service
      - discovery-service
#    restart: always
    networks:
      - msa-network

networks:
  msa-network:
    driver: bridge
