version: "3.6"
services:

  discovery-service:
    container_name: discovery-service
    image: eureka:0.1
    ports:
      - "8761:8761"
    networks:
      - docker-network

  gateway-service:
    container_name: gateway-service
    image: apigateway:0.1
    environment:
      eureka.client.serviceUrl.defaultZone: "http://discovery-service:8761/eureka/"
    ports:
      - "9000:9000"
    networks:
      - docker-network
    depends_on:
      - discovery-service

  docker-controll-service:
    container_name: docker-controll-service
    image: docker-controll:0.1
    environment:
      eureka.client.serviceUrl.defaultZone: "http://discovery-service:8761/eureka/"
    ports:
      - "8010:8010"
    networks:
      - docker-network
    depends_on:
      - gateway-service
      - discovery-service

networks:
  docker-network:
    external: true
