version: "3.6"
services:

  discovery-service:
    container_name: discovery-service
    build:
      context: ./discovery-service/
      dockerfile: Dockerfile
    ports:
      - "8761:8761"
    networks:
      - docker-network

  gateway-service:
    container_name: gateway-service
    build:
      context: ./gateway-servicee/
      dockerfile: Dockerfile
    environment:
      eureka.client.serviceUrl.defaultZone: "http://discovery-service:8761/eureka/"
    ports:
      - "9000:9000"
    networks:
      - docker-network
    depends_on:
      - discovery-service

  docker-controll-service:
    container_name: docker-controll-service
    image: docker-controll:0.1
    environment:
      eureka.client.serviceUrl.defaultZone: "http://discovery-service:8761/eureka/"
    ports:
      - "8010:8010"
    networks:
      - docker-network
    depends_on:
      - gateway-service
      - discovery-service

  user-service:
    container_name: user
    build:
      context: ./user-service/
      dockerfile: Dockerfile
    environment:
      - eureka.client.serviceUrl.defaultZone=http://discovery-service:8761/eureka/
    ports:
      - "8030:8030"
    depends_on:
      - gateway-service
      - discovery-service
    restart: always
    networks:
      - docker-network

networks:
  docker-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.18.0.0/16
          gateway: 172.18.0.1
