server:
  port: 9000

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defalutZone: http://localhost:8761/eureka

spring:
  application:
    name: apigateway-service

  cloud:
    gateway:
      default-filters:
        - GlobalFilter
      routes:
        - id: spring-service
          uri: lb://SPRING-SERVICE
          predicates:
            - Path=/spring-service/**
          filters:
            - BFFServiceCustomFilter
#              https://docs.spring.io/spring-cloud-gateway/docs/current/reference/html/#the-deduperesponseheader-gatewayfilter-factory
#            - AddRequestHeader=X-Request-red, blue

management:
  endpoints:
    web:
      exposure:
        include: health, info, metrics, prometheus, gateway
