eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/discovery/eureka

spring:
  application:
    name: gateway-service

  cloud:
    gateway:
#      default-filters:
#        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials
      default-filters:
        - name: GlobalFilter
          args:
            preLogInfo: true
            postLogInfo: true
            enableCors: true
###    web-service와 통신할 때 필요한 cors설정
#      globalcors:
#        cors-configurations:
#          '[/**]':
#            allowedOrigins: "http://localhost:3000"
#            allowedMethods:
#              - GET
#              - POST
#              - PUT
#              - DELETE
#            allowedHeaders:
#              - Content-Type
#              - Authorization
#            allowCredentials: true
#            maxAge: 3600
      routes:
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/gateway/user-service/**
          filters:
            - RewritePath=/gateway/user-service/(?<segment>.*),/$\{segment}
        - id: batch-service
          uri: lb://BATCH-SERVICE
          predicates:
            - Path=/gateway/batch-service/**
          filters:
            - JwtAuthorizationCheckFilter
            - RewritePath=/gateway/batch-service/(?<segment>.*),/$\{segment}
        - id: business-service
          uri: lb://BUSINESS-SERVICE
          predicates:
            - Path=/gateway/business-service/**
          filters:
            - JwtAuthorizationCheckFilter
            - RewritePath=/gateway/business-service/(?<segment>.*),/$\{segment}
