apiVersion: v1
kind: Service
metadata:
  name: kubernetes-service
  namespace: msa-ns
spec:
  selector:
    app: msa-kubernetes
  ports:
    - port: 8030
      targetPort: 8030
#  externalIPs:
#    - ${node_ip}
