apiVersion: v1
kind: Service
metadata:
  name: business-service
  namespace: msa-ns
spec:
  selector:
    app: msa-business
  ports:
    - port: 8030
      targetPort: 8030
#  externalIPs:
#    - ${node_ip}
