apiVersion: v1
kind: Service
metadata:
  name: discovery-service
  namespace: msa-ns
spec:
  selector:
    app: msa-discovery
  ports:
    - port: 8761
      targetPort: 8761
# externalIPs:
#    - ${node_ip}
