apiVersion: v1
kind: Service
metadata:
  name: gateway-service
  namespace: msa-ns
spec:
  selector:
    app: msa-gateway
  ports:
    - port: 9000
      targetPort: 9000
# externalIPs:
#    - ${node_ip}
