apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deployment
  labels:
    app: msa-postgres
  namespace: msa-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: msa-postgres
  template:
    metadata:
      labels:
        app: msa-postgres
    spec:
#      nodeSelector:
#        msa-node: "true"
      containers:
      - image: jinmanpark/spring-cloud-msa-postgres:v20240405
        name: postgres
        ports:
        - containerPort: 5432
        resources: {}
      restartPolicy: Always
