server:
  port: 8030

spring:
  profiles:
    active: dev
    include:
      - springdoc
    group:
      dev: springdoc-dev
      prod: springdoc-prod

  application:
    name: business-service

  zipkin:
    base-url: http://127.0.0.1:9411
    enabled: true

management:
  tracing:
    sampling:
      probability: 1.0
    propagation:
      consume: b3_multi
      produce: b3_multi
  zipkin:
    tracing:
      endpoint: "http://zipkin:9411/api/v2/spans"
  endpoints:
    web:
      exposure:
        include: health, httptrace, info, metrics, prometheus

logging:
  pattern:
    level: "%5p [%X{traceId:-},%X{spanId:-}]"
