eureka:
  instance:
    prefer-ip-address: true
    hostname: business-service
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://discovery-service:8761/discovery/eureka/

spring:
  jpa:
    hibernate:
      ddl-auto: create
    generate-ddl: true
    open-in-view: false
    properties:
      hibernate:
        default_batch_fetch_size: 1000
        dialect: org.hibernate.dialect.PostgreSQLDialect

  datasource:
    url: jdbc:postgresql://postgres:5432/postgres
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: 1234
