server:
  port: 9000

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defalutZone: http://localhost:8761/eureka

spring:
  application:
    name: gateway-service

  cloud:
    gateway:
      default-filters:
        - GlobalFilter
      routes:
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/user-service/**
          filters:
            - BFFServiceCustomFilter
#              https://docs.spring.io/spring-cloud-gateway/docs/current/reference/html/#the-deduperesponseheader-gatewayfilter-factory
#            - AddRequestHeader=X-Request-red, blue
        - id: batch-service
          uri: lb://BATCH-SERVICE
          predicates:
            - Path=/batch-service/**
        - id: docker-service
          uri: lb://DOCKER-SERVICE
          predicates:
            - Path=/docker-service/**

management:
  endpoints:
    web:
      exposure:
        include: health, info, metrics, prometheus, gateway
