server:
  port: 9000

management:
  endpoint:
    web:
      exposure:
        include: info, health, metrics, prometheus
  atlas:
    metrics:
      export:
        enabled: false

spring:
  profiles:
    active: dev

  application:
    name: gateway-service

jwt:
  token:
    secret: c3ByaW5nLWJvb3Qtc3ByaW5nLWNsb3VkLW1zYS11c2VyLXNlcnZpY2Utc3ByaW5nLXNlY3VyaXR5LWp3dC10ZXN0Cg==
