server:
  port: 9000

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defalutZone: http://localhost:8761/eureka

spring:
  application:
    name: gateway-service

  cloud:
    gateway:
      default-filters:
        - name: GlobalFilter
          args:
            preLogInfo: true
            postLogInfo: true
      routes:
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/user-service/**
          filters:
            - JwtAuthorizationCheckFilter
            - RewritePath=/user-service/(?<segment>.*),/$\{segment}
#              https://docs.spring.io/spring-cloud-gateway/docs/current/reference/html/#the-deduperesponseheader-gatewayfilter-factory
#            - AddRequestHeader=X-Request-red, blue
        - id: batch-service
          uri: lb://BATCH-SERVICE
          predicates:
            - Path=/batch-service/**
          filters:
            - JwtAuthorizationCheckFilter
            - RewritePath=/batch-service/(?<segment>.*),/$\{segment}
        - id: docker-control-service
          uri: lb://DOCKER-CONTROL-SERVICE
          predicates:
            - Path=/docker-control-service/**
          filters:
            - JwtAuthorizationCheckFilter
            - RewritePath=/docker-control-service/(?<segment>.*),/$\{segment}

management:
  endpoints:
    web:
      exposure:
        include: health, info, metrics, prometheus, gateway

jwt:
  token:
    secret: c3ByaW5nLWJvb3Qtc3ByaW5nLWNsb3VkLW1zYS11c2VyLXNlcnZpY2Utc3ByaW5nLXNlY3VyaXR5LWp3dC10ZXN0Cg==
