server:
  port: 8020

thread:
  pool:
    size: 1

spring:
  profiles:
    active: dev

  application:
    name: batch-service

  zipkin:
    base-url: http://127.0.0.1:9411
    enabled: true

management:
  tracing:
    sampling:
      probability: 1.0
    propagation:
      consume: b3_multi
      produce: b3_multi
  zipkin:
    tracing:
      endpoint: "http://zipkin:9411/api/v2/spans"

logging:
  pattern:
    level: "%5p [%X{traceId:-},%X{spanId:-}]"
